### PR TITLE
Update store to use latest istio client

### PR DESCRIPTION
**Pull request by thomasv314**

### CODE REVIEW

**Comment by thomasv314** [comment]
Closing to reopen against kubernetes-sigs/external-dns in hopes of getting test output

**Comment by thomasv314** [comment]
Bah, apologies @sagor999,  I forgot about `/ok-to-test`, so I'm gonna re-open and PR against this.

`make test` passes with this branch, but i'm still not seeing the functionality intended

Will push update here once I've gotten that far.

**Comment by sagor999** [comment]
@thomasv314 Let me know if you have any questions!

**Comment by thomasv314** [comment]
@sagor999 thanks! i rebased from master upstream and have a passing test suite, do you mind rebasing `sagor999:k8s-1.16.7-support`? i'll resolve any conflicts in my branch afterwards

**Comment by sagor999** [comment]
@thomasv314 I rebased `sagor999:k8s-1.16.7-support ` to latest.

**Comment by thomasv314** [comment]
@sagor999 I appreciate the swift response! can confirm this branch is working in my dev cluster with istio 1.5.1 👌

**Pull request closed without merging**
